#!/usr/bin/env python3

import subprocess
import optparse
import re

parser = optparse.OptionParser()

parser.add_option("-i","--interface",dest="interface", help="Interface to change MAC Address")
parser.add_option("-m","--mac",dest="new_mac", help="New MAC Address that is to be set")

(options, args) = parser.parse_args()
if(options.interface is None):
    parser.error("[-] Please specify an interface, use --help for more info")
elif(options.new_mac is None):
    parser.error("[-] Please specify a new mac address, use --help for more info")

def change_mac(interface,new_mac):
    print("[+] Changing MAC address for " + interface + " to: " + new_mac)

    subprocess.call(["ifconfig", interface,"down"])
    subprocess.call(["ifconfig",interface,"hw","ether",new_mac])
    subprocess.call(["ifconfig",interface,"up"])

change_mac(options.interface,options.new_mac)

output_ifconfig = subprocess.check_output(["ifconfig", options.interface])

mac_search_result  = re.search(r"\w\w:\w\w:\w\w:\w\w:\w\w:\w\w", output_ifconfig.decode("utf-8"))


if(mac_search_result is not None):
    print("[+] New MAC Address set to: ")
    print(mac_search_result.group(0))
else:
    print("[-] Could not read MAC Address.")

if(mac_search_result.group(0) == options.new_mac):
    print("[+] MAC Address changed succesfully")
else:
    print("[-] Oops, something unknown went wrong, try again")
